/*
 * Author: Rory
 * Initializes Virtual Arsenal on an object with specific items only.
 *
 * Arguments:
 * 0: Crate <OBJECT>
 *
 * Return Value:
 * None
 *
 * Example:
 * [crate] call TAC_Olympus_fnc_ArmoryBoxMGInit
 */
#include "..\script_component.hpp"

params ["_crate"];

[_crate, [
    // Rifles
    ["rifle", "LMG_Mk200_F", "Machine Gun", "", 1],
    ["rifle", "arifle_MX_SW_F", "Machine Gun", "", 1],
    ["rifle", "hlc_rifle_rpk", "Machine Gun", "", 1],
    ["rifle", "arifle_MX_SW_Black_F", "Machine Gun", "", 1],
    ["rifle", "hlc_rifle_rpk12", "Machine Gun", "", 1],
    ["rifle", "hlc_lmg_minimi_railed", "Machine Gun", "", 1],
    ["rifle", "hlc_m249_pip1", "Machine Gun", "", 1],
    ["rifle", "hlc_m249_pip2", "Machine Gun", "", 1],
    ["rifle", "hlc_m249_pip3", "Machine Gun", "", 1],
    ["rifle", "hlc_m249_pip4", "Machine Gun", "", 1],
    // Magazines
    ["ammo", "ACE_200Rnd_65x39_cased_Box_Tracer_Dim", "Machine Gun Ammo", "", 1],
    ["ammo", "30Rnd_65x39_caseless_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_30Rnd_65x39_caseless_mag_Tracer_Dim", "Machine Gun Ammo", "", 1],
    ["ammo", "100Rnd_65x39_caseless_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_100Rnd_65x39_caseless_mag_Tracer_Dim", "Machine Gun Ammo", "", 1],
    ["ammo", "30rnd_556x45_stanag", "Machine Gun Ammo", "", 1],
    ["ammo", "6Rnd_45ACP_Cylinder", "Machine Gun Ammo", "", 1],
    ["ammo", "20rnd_556x45_uw_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_30Rnd_65x39_caseless_green_mag_Tracer_D", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_30Rnd_556x45_Stanag_M995_AP_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_30Rnd_556x45_Stanag_Mk262_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_30Rnd_556x45_Stanag_Mk318_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_30Rnd_556x45_Stanag_Tracer_Dim", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x51_Mag_Tracer", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x51_Mag_Tracer_Dim", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x51_Mag_SD", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_10Rnd_762x51_M118LR_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_10Rnd_762x51_Mk316_Mod_0_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_10Rnd_762x51_Mk319_Mod_0_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_10Rnd_762x51_M993_AP_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x51_M118LR_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x51_M993_AP_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x67_Mk248_Mod_0_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x67_Mk248_Mod_1_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_20Rnd_762x67_Berger_Hybrid_OTM_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_10Rnd_338_300gr_HPBT_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_10Rnd_338_API526_Mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_10Rnd_762x54_Tracer_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_30Rnd_9x19_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "ACE_16Rnd_9x19_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "29Round_300BLK_STANAG", "Machine Gun Ammo", "", 1],
    ["ammo", "29Round_300BLK_STANAG_T", "Machine Gun Ammo", "", 1],
    ["ammo", "29Round_300BLK_STANAG_S", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_556x45_EPR", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_556x45_SOST", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_556x45_SPR", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_B_fal", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_t_fal", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_S_fal", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_50Rnd_762x51_M_FAL", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_B_G3", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_T_G3", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_50Rnd_762x51_M_G3", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_B_M14", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_T_M14", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_545x39_B_AK", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_545x39_T_AK", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_545x39_EP_AK", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_45Rnd_545x39_t_rpk", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_762x39_b_ak", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_762x39_t_ak", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_45Rnd_762x39_t_rpk", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_45Rnd_762x39_m_rpk", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_9x19_B_MP5", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_9x19_GD_MP5", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_9x19_SD_MP5", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_10mm_B_MP5", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_10mm_JHP_MP5", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_556x45_B_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_556x45_SOST_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_556x45_SPR_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_556x45_T_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_40Rnd_556x45_B_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_40Rnd_556x45_SOST_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_40Rnd_556x45_SPR_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_25Rnd_9x19mm_M882_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_25Rnd_9x19mm_JHP_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_25Rnd_9x19mm_subsonic_AUG", "Machine Gun Ammo", "", 1],
    ["ammo", "30rnd_9x21_mag", "Machine Gun Ammo", "", 1],
    ["ammo", "30rnd_45acp_mag_smg_01", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30Rnd_545x39_S_AK", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_10rnd_12g_buck_S12", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_10rnd_12g_slug_S12", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_200rnd_556x45_M_SAW", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_200rnd_556x45_T_SAW", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_200rnd_556x45_B_SAW", "Machine Gun Ammo", "", 1],
    ["ammo", "150rnd_762x54_box", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30rnd_556x45_EPR_G36", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30rnd_556x45_SOST_G36", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_30rnd_556x45_SPR_G36", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_100rnd_556x45_EPR_G36", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_5rnd_3006_1903", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_24Rnd_75x55_B_stgw", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_24Rnd_75x55_ap_stgw", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_b_amt", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_mk316_amt", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_bball_amt", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_20Rnd_762x51_T_amt", "Machine Gun Ammo", "", 1],
    ["ammo", "hlc_24Rnd_75x55_T_stgw", "Machine Gun Ammo", "", 1],
    // Attachments
    ["attachment", "RH_HBLM", "Attachment", "", 1],
    ["attachment", "RH_HBLM_tg", "Attachment", "", 1],
    ["attachment", "RH_HBLM_des", "Attachment", "", 1],
    ["attachment", "RH_HBLM_wdl", "Attachment", "", 1],
    ["attachment", "RH_TD_ACB", "Attachment", "", 1],
    ["attachment", "RH_TD_ACB_g", "Attachment", "", 1],
    ["attachment", "RH_TD_ACB_b", "Attachment", "", 1],
    ["attachment", "optic_Yorris", "Attachment", "", 1],
    ["attachment", "optic_MRD", "Attachment", "", 1],
    ["attachment", "acc_flashlight", "Attachment", "", 1],
    ["attachment", "ACE_acc_pointer_red", "Attachment", "", 1],
    ["attachment", "ACE_acc_pointer_green_IR", "Attachment", "", 1],
    ["attachment", "ACE_acc_pointer_green", "Attachment", "", 1],
    ["attachment", "RH_peq15", "Attachment", "", 1],
    ["attachment", "RH_peq15_top", "Attachment", "", 1],
    ["attachment", "RH_peq15b", "Attachment", "", 1],
    ["attachment", "RH_peq15b_top", "Attachment", "", 1],
    ["attachment", "RH_peq2", "Attachment", "", 1],
    ["attachment", "RH_peq2_top", "Attachment", "", 1],
    ["attachment", "RH_SFM952V", "Attachment", "", 1],
    ["attachment", "RH_SFM952V_tan", "Attachment", "", 1],
    ["attachment", "RH_pmir", "Attachment", "", 1],
    ["attachment", "RH_A26", "Attachment", "", 1],
    ["attachment", "RH_x2", "Attachment", "", 1],
    ["attachment", "RH_m6x", "Attachment", "", 1],
    ["attachment", "optic_Aco", "Attachment", "", 1],
    ["attachment", "optic_ACO_grn", "Attachment", "", 1],
    ["attachment", "optic_Arco", "Attachment", "", 1],
    ["attachment", "optic_Hamr", "Attachment", "", 1],
    ["attachment", "optic_MRCO", "Attachment", "", 1],
    ["attachment", "optic_Holosight", "Attachment", "", 1],
    ["attachment", "ACE_optic_Arco_2D", "Attachment", "", 1],
    ["attachment", "ACE_optic_SOS_2D", "Attachment", "", 1],
    ["attachment", "ACE_optic_MRCO_2D", "Attachment", "", 1],
    ["attachment", "ACE_optic_Hamr_2D", "Attachment", "", 1],
    ["attachment", "hlc_optic_suit", "Attachment", "", 1],
    ["attachment", "hlc_optic_accupoint_g3", "Attachment", "", 1],
    ["attachment", "hlc_optic_kobra", "Attachment", "", 1],
    ["attachment", "hlc_optic_goshawk", "Attachment", "", 1],
    ["attachment", "optic_ACO_grn_smg", "Attachment", "", 1],
    ["attachment", "optic_Aco_smg", "Attachment", "", 1],
    ["attachment", "optic_Holosight_smg", "Attachment", "", 1],
    ["attachment", "RH_eotech553", "Attachment", "", 1],
    ["attachment", "RH_eotech553mag", "Attachment", "", 1],
    ["attachment", "RH_eotech553_tan", "Attachment", "", 1],
    ["attachment", "RH_eotech553mag_tan", "Attachment", "", 1],
    ["attachment", "RH_eotexps3", "Attachment", "", 1],
    ["attachment", "RH_eotexps3_tan", "Attachment", "", 1],
    ["attachment", "RH_eothhs1", "Attachment", "", 1],
    ["attachment", "RH_eothhs1_tan", "Attachment", "", 1],
    ["attachment", "RH_compm4s", "Attachment", "", 1],
    ["attachment", "RH_compm2", "Attachment", "", 1],
    ["attachment", "RH_compm2l", "Attachment", "", 1],
    ["attachment", "RH_compm2_tan", "Attachment", "", 1],
    ["attachment", "RH_compm2l_tan", "Attachment", "", 1],
    ["attachment", "RH_t1", "Attachment", "", 1],
    ["attachment", "RH_t1_tan", "Attachment", "", 1],
    ["attachment", "RH_reflex", "Attachment", "", 1],
    ["attachment", "RH_shortdot", "Attachment", "", 1],
    ["attachment", "RH_m3lr", "Attachment", "", 1],
    ["attachment", "RH_ta01nsn", "Attachment", "", 1],
    ["attachment", "RH_ta01nsn_2D", "Attachment", "", 1],
    ["attachment", "RH_ta31rco", "Attachment", "", 1],
    ["attachment", "RH_ta31rco_2D", "Attachment", "", 1],
    ["attachment", "RH_ta31rmr", "Attachment", "", 1],
    ["attachment", "RH_ta31rmr_2D", "Attachment", "", 1],
    ["attachment", "RH_ta01nsn_tan", "Attachment", "", 1],
    ["attachment", "RH_ta01nsn_tan_2D", "Attachment", "", 1],
    ["attachment", "RH_ta31rco_tan", "Attachment", "", 1],
    ["attachment", "RH_ta31rco_tan_2D", "Attachment", "", 1],
    ["attachment", "RH_ta31rmr_tan", "Attachment", "", 1],
    ["attachment", "RH_ta31rmr_tan_2D", "Attachment", "", 1],
    ["attachment", "RH_ta648", "Attachment", "", 1],
    ["attachment", "RH_accupoint", "Attachment", "", 1],
    ["attachment", "RH_c79", "Attachment", "", 1],
    ["attachment", "RH_c79_2D", "Attachment", "", 1],
    ["attachment", "RH_m145", "Attachment", "", 1],
    ["attachment", "RH_barska_rds", "Attachment", "", 1],
    ["attachment", "RH_cmore", "Attachment", "", 1],
    ["attachment", "RH_Ltdocter", "Attachment", "", 1],
    ["attachment", "RH_LTdocterl", "Attachment", "", 1],
    ["attachment", "RH_zpoint", "Attachment", "", 1],
    ["attachment", "HLC_Optic_G36dualoptic35x", "Attachment", "", 1],
    ["attachment", "HLC_Optic_G36dualoptic35x2d", "Attachment", "", 1],
    ["attachment", "HLC_Optic_G36Export35x", "Attachment", "", 1],
    ["attachment", "HLC_Optic_G36Export35x2d", "Attachment", "", 1],
    ["attachment", "HLC_Optic_G36Dualoptic15x", "Attachment", "", 1],
    ["attachment", "HLC_Optic_G36Dualoptic15x2d", "Attachment", "", 1],
    ["attachment", "HLC_Optic_G36Export15x", "Attachment", "", 1],
    ["attachment", "HLC_Optic_G36Export15x2d", "Attachment", "", 1],
    ["attachment", "hlc_optic_Kern", "Attachment", "", 1],
    ["attachment", "hlc_optic_Kern2d", "Attachment", "", 1],
    ["attachment", "bipod_01_F_snd", "Attachment", "", 1],
    ["attachment", "bipod_01_F_blk", "Attachment", "", 1],
    ["attachment", "bipod_01_F_mtp", "Attachment", "", 1],
    ["attachment", "RH_HBLM", "Attachment", "", 1],
    ["attachment", "RH_HBLM_tg", "Attachment", "", 1],
    ["attachment", "RH_HBLM_des", "Attachment", "", 1],
    ["attachment", "RH_HBLM_wdl", "Attachment", "", 1],
    ["attachment", "RH_TD_ACB", "Attachment", "", 1],
    ["attachment", "RH_TD_ACB_b", "Attachment", "", 1],
    ["attachment", "RH_TD_ACB_g", "Attachment", "", 1],
    // Backpacks
    ["backpack", "tacs_Backpack_AssaultExpanded_Black", "Backpack", "", 1],
    ["backpack", "tacs_Backpack_AssaultExpanded_Green", "Backpack", "", 1],
    ["backpack", "tacs_Backpack_AssaultExpanded_Tan", "Backpack", "", 1],
    ["backpack", "tacs_Backpack_Carryall_DarkBlack", "Backpack", "", 1],
    ["backpack", "tacs_Backpack_Kitbag_DarkBlack", "Backpack", "", 1]
]] call TACFUNC(armory,addItems);
