/*
 * Author: Rory
 * Initializes Virtual Arsenal on an object with specific items only.
 *
 * Arguments:
 * 0: Crate <OBJECT>
 *
 * Return Value:
 * None
 *
 * Example:
 * [crate] call TAC_Olympus_fnc_ArmoryBoxStagingInit
 */
#include "..\script_component.hpp"

params ["_crate"];

[_crate, [
    // Uniforms
    ["wearable", "U_B_HeliPilotCoveralls", "Uniform", "", 5],
    ["wearable", "U_I_HeliPilotCoveralls", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_BS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_BS_GP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_BS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_BS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_GS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_GS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_BS_DGP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_TS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_TS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_TS_GP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_CDBS_GP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_CLBS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_CLRS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_LS_CPS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_BS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_BS_GP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_BS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_BS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_GS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_GS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_BS_DGP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_TS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_TS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_TS_GP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_CDBS_GP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_CLBS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_CLRS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Combat_RS_CPS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_BS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_BS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_BS_EP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_GS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_GS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_GS_EP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_ES_EP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_ES_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_ES_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_TS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_GS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_TS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_BS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_LS_TS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_BS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_BS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_BS_EP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_GS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_GS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_GS_EP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_ES_EP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_ES_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_ES_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_TS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_GS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_TS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_BS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Garment_RS_TS_BP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_LS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_TS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_BS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_BS_LP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_LS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_OS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_OS_LP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_GS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_WS_TP_TB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_WS_LP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_TP_WS_GP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_CP_LS_TP_OB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_CP_RS_LP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_Polo_CP_BS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_TShirt_JP_GS_LP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_TShirt_JP_GS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_TShirt_JP_BS_LP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_TShirt_JP_BS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_TShirt_JP_LS_TP_BB", "Uniform", "", 5],
    ["wearable", "tacs_Uniform_TShirt_JP_WS_LP_BB", "Uniform", "", 5],
    // Goggles
    ["wearable", "G_Shades_Black", "Goggles", "", 5],
    ["wearable", "G_Shades_Blue", "Goggles", "", 5],
    ["wearable", "G_Sport_Blackred", "Goggles", "", 5],
    ["wearable", "G_Spectacles", "Goggles", "", 5],
    ["wearable", "G_Spectacles_Tinted", "Goggles", "", 5],
    ["wearable", "G_Combat", "Goggles", "", 5],
    ["wearable", "G_Lowprofile", "Goggles", "", 5],
    ["wearable", "G_Shades_Green", "Goggles", "", 5],
    ["wearable", "G_Shades_Red", "Goggles", "", 5],
    ["wearable", "G_Sport_BlackWhite", "Goggles", "", 5],
    ["wearable", "G_Sport_Blackyellow", "Goggles", "", 5],
    ["wearable", "G_Sport_Greenblack", "Goggles", "", 5],
    ["wearable", "G_Sport_Checkered", "Goggles", "", 5],
    ["wearable", "G_Sport_Red", "Goggles", "", 5],
    ["wearable", "G_Tactical_Black", "Goggles", "", 5],
    ["wearable", "G_Bandanna_aviator", "Goggles", "", 5],
    ["wearable", "G_Bandanna_blk", "Goggles", "", 5],
    ["wearable", "G_Bandanna_khk", "Goggles", "", 5],
    ["wearable", "G_Bandanna_oli", "Goggles", "", 5],
    ["wearable", "G_Bandanna_shades", "Goggles", "", 5],
    ["wearable", "G_Bandanna_sport", "Goggles", "", 5],
    ["wearable", "G_Bandanna_tan", "Goggles", "", 5],
    ["wearable", "ACE_NVG_Gen1", "Goggles", "", 5],
    ["wearable", "ACE_NVG_Gen2", "Goggles", "", 5],
    ["wearable", "ACE_NVG_Gen4", "Goggles", "", 5],
    ["wearable", "ACE_NVG_Wide", "Goggles", "", 5],
    ["wearable", "G_Aviator", "Goggles", "", 5],
    ["wearable", "NVGoggles_OPFOR", "Goggles", "", 5],
    ["wearable", "NVGoggles", "Goggles", "", 5],
    ["wearable", "NVGoggles_INDEP", "Goggles", "", 5],
    ["wearable", "tacs_Goggles_Black", "Goggles", "", 5],
    ["wearable", "tacs_Goggles_Green", "Goggles", "", 5],
    ["wearable", "tacs_Goggles_Tan", "Goggles", "", 5],
    // Backpacks
    ["backpack", "B_AssaultPack_blk", "Backpack", "", 5],
    ["backpack", "B_AssaultPack_cbr", "Backpack", "", 5],
    ["backpack", "B_AssaultPack_mcamo", "Backpack", "", 5],
    ["backpack", "B_AssaultPack_ocamo", "Backpack", "", 5],
    ["backpack", "B_AssaultPack_rgr", "Backpack", "", 5],
    ["backpack", "B_AssaultPack_sgg", "Backpack", "", 5],
    ["backpack", "B_FieldPack_ocamo_Medic", "Backpack", "", 5],
    ["backpack", "B_Carryall_ocamo", "Backpack", "", 5],
    ["backpack", "B_Carryall_oli", "Backpack", "", 5],
    ["backpack", "B_Carryall_cbr", "Backpack", "", 5],
    ["backpack", "B_Kitbag_sgg", "Backpack", "", 5],
    ["backpack", "B_Kitbag_mcamo", "Backpack", "", 5],
    ["backpack", "B_FieldPack_blk", "Backpack", "", 5],
    ["backpack", "B_FieldPack_ocamo", "Backpack", "", 5],
    ["backpack", "B_FieldPack_oucamo", "Backpack", "", 5],
    ["backpack", "B_FieldPack_cbr", "Backpack", "", 5],
    ["backpack", "tacs_Backpack_AssaultExpanded_Black", "Backpack", "", 5],
    ["backpack", "tacs_Backpack_AssaultExpanded_Green", "Backpack", "", 5],
    ["backpack", "tacs_Backpack_AssaultExpanded_Tan", "Backpack", "", 5],
    ["backpack", "tacs_Backpack_Carryall_DarkBlack", "Backpack", "", 5],
    ["backpack", "tacs_Backpack_Kitbag_DarkBlack", "Backpack", "", 5],
    // Headgear
    ["wearable", "H_Booniehat_khk_hs", "Headgear", "", 5],
    ["wearable", "H_Booniehat_khk", "Headgear", "", 5],
    ["wearable", "H_HelmetB", "Headgear", "", 5],
    ["wearable", "H_HelmetB_light", "Headgear", "", 5],
    ["wearable", "H_HelmetB_paint", "Headgear", "", 5],
    ["wearable", "H_PilotHelmetHeli_B", "Headgear", "", 5],
    ["wearable", "H_PilotHelmetHeli_O", "Headgear", "", 5],
    ["wearable", "H_CrewHelmetHeli_B", "Headgear", "", 5],
    ["wearable", "H_Cap_red", "Headgear", "", 5],
    ["wearable", "H_Cap_blu", "Headgear", "", 5],
    ["wearable", "H_Cap_oli", "Headgear", "", 5],
    ["wearable", "H_Cap_headphones", "Headgear", "", 5],
    ["wearable", "H_Cap_tan", "Headgear", "", 5],
    ["wearable", "H_Cap_blk", "Headgear", "", 5],
    ["wearable", "H_Cap_brn_SPECOPS", "Headgear", "", 5],
    ["wearable", "H_Cap_tan_specops_US", "Headgear", "", 5],
    ["wearable", "H_Cap_khaki_specops_UK", "Headgear", "", 5],
    ["wearable", "H_Cap_grn", "Headgear", "", 5],
    ["wearable", "H_Cap_blk_Raven", "Headgear", "", 5],
    ["wearable", "H_Cap_oli_hs", "Headgear", "", 5],
    ["wearable", "H_Cap_usblack", "Headgear", "", 5],
    ["wearable", "H_Bandanna_khk", "Headgear", "", 5],
    ["wearable", "H_Bandanna_khk_hs", "Headgear", "", 5],
    ["wearable", "H_Bandanna_cbr", "Headgear", "", 5],
    ["wearable", "H_Bandanna_sgg", "Headgear", "", 5],
    ["wearable", "H_Bandanna_sand", "Headgear", "", 5],
    ["wearable", "H_Bandanna_gry", "Headgear", "", 5],
    ["wearable", "H_Bandanna_blu", "Headgear", "", 5],
    ["wearable", "H_Bandanna_camo", "Headgear", "", 5],
    ["wearable", "H_Bandanna_mcamo", "Headgear", "", 5],
    ["wearable", "H_Booniehat_oli", "Headgear", "", 5],
    ["wearable", "H_Watchcap_blk", "Headgear", "", 5],
    ["wearable", "H_Watchcap_camo", "Headgear", "", 5],
    ["wearable", "H_Watchcap_cbr", "Headgear", "", 5],
    ["wearable", "H_Watchcap_khk", "Headgear", "", 5],
    ["wearable", "H_Booniehat_DMARPAT", "Headgear", "", 5],
    ["wearable", "H_Booniehat_GCAMO", "Headgear", "", 5],
    ["wearable", "H_Booniehat_rgr", "Headgear", "", 5],
    ["wearable", "H_CrewHelmetHeli_O", "Headgear", "", 5],
    ["wearable", "H_HelmetB_plain_blk", "Headgear", "", 5],
    ["wearable", "H_Helmet_Kerry", "Headgear", "", 5],
    ["wearable", "H_HelmetB_black", "Headgear", "", 5],
    ["wearable", "H_HelmetB_desert", "Headgear", "", 5],
    ["wearable", "H_HelmetB_grass", "Headgear", "", 5],
    ["wearable", "H_HelmetB_sand", "Headgear", "", 5],
    ["wearable", "H_HelmetB_snakeskin", "Headgear", "", 5],
    ["wearable", "H_HelmetIA", "Headgear", "", 5],
    ["wearable", "tacs_Cap_Headphones_BlackLogo", "Headgear", "", 5],
    ["wearable", "tacs_Cap_BlackLogo", "Headgear", "", 5],
    ["wearable", "tacs_Cap_TanLogo", "Headgear", "", 5],
    ["wearable", "tacs_Cap_Earpiece_BlackLogo", "Headgear", "", 5],
    ["wearable", "tacs_Cap_Earpiece_TanLogo", "Headgear", "", 5],
    ["wearable", "tacs_Cap_Backwards_BlackLogo", "Headgear", "", 5],
    ["wearable", "tacs_Cap_Backwards_TanLogo", "Headgear", "", 5],
    ["wearable", "tacs_Helmet_Ballistic_DarkBlack", "Headgear", "", 5],
    ["wearable", "tacs_Helmet_PilotHeli_Tan", "Headgear", "", 5],
    ["wearable", "tacs_Hat_Boonie_RangerGreen", "Headgear", "", 5],
    ["wearable", "tacs_Hat_Boonie_DesertMARPAT", "Headgear", "", 5],
    ["wearable", "tacs_Hat_Boonie_Woodland", "Headgear", "", 5],
    ["wearable", "tacs_Hat_Boonie_UCP", "Headgear", "", 5],
    // Vests
    ["wearable", "V_PlateCarrier1_rgr", "Vest", "", 5],
    ["wearable", "V_PlateCarrier2_rgr", "Vest", "", 5],
    ["wearable", "V_TacVest_brn", "Vest", "", 5],
    ["wearable", "V_TacVest_oli", "Vest", "", 5],
    ["wearable", "V_PlateCarrierH_CTRG", "Vest", "", 5],
    ["wearable", "V_PlateCarrierL_CTRG", "Vest", "", 5],
    ["wearable", "V_RebreatherB", "Vest", "", 5],
    ["wearable", "V_Rangemaster_belt", "Vest", "", 5],
    ["wearable", "V_BandollierB_khk", "Vest", "", 5],
    ["wearable", "V_BandollierB_cbr", "Vest", "", 5],
    ["wearable", "V_BandollierB_rgr", "Vest", "", 5],
    ["wearable", "V_BandollierB_blk", "Vest", "", 5],
    ["wearable", "V_BandollierB_oli", "Vest", "", 5],
    ["wearable", "V_PlateCarrier3_rgr", "Vest", "", 5],
    ["wearable", "V_PlateCarrierGL_rgr", "Vest", "", 5],
    ["wearable", "V_PlateCarrier1_blk", "Vest", "", 5],
    ["wearable", "V_PlateCarrierSpec_rgr", "Vest", "", 5],
    ["wearable", "V_Chestrig_khk", "Vest", "", 5],
    ["wearable", "V_Chestrig_rgr", "Vest", "", 5],
    ["wearable", "V_Chestrig_blk", "Vest", "", 5],
    ["wearable", "V_Chestrig_oli", "Vest", "", 5],
    ["wearable", "V_TacVest_khk", "Vest", "", 5],
    ["wearable", "V_TacVest_blk", "Vest", "", 5],
    ["wearable", "V_TacVest_camo", "Vest", "", 5],
    ["wearable", "V_TacVestIR_blk", "Vest", "", 5],
    ["wearable", "V_TacVestCamo_khk", "Vest", "", 5],
    ["wearable", "V_HarnessO_brn", "Vest", "", 5],
    ["wearable", "V_HarnessOGL_brn", "Vest", "", 5],
    ["wearable", "V_HarnessO_gry", "Vest", "", 5],
    ["wearable", "V_HarnessOGL_gry", "Vest", "", 5],
    ["wearable", "V_HarnessOSpec_brn", "Vest", "", 5],
    ["wearable", "V_HarnessOSpec_gry", "Vest", "", 5],
    ["wearable", "V_PlateCarrierIA1_dgtl", "Vest", "", 5],
    ["wearable", "V_PlateCarrierIA2_dgtl", "Vest", "", 5],
    ["wearable", "tacs_Vest_PlateCarrierFull_Black", "Vest", "", 5],
    ["wearable", "tacs_Vest_PlateCarrierFull_Green", "Vest", "", 5],
    ["wearable", "tacs_Vest_PlateCarrier_Black", "Vest", "", 5],
    ["wearable", "tacs_Vest_PlateCarrier_Green", "Vest", "", 5],
    ["wearable", "tacs_Vest_PlateCarrier_Coyote", "Vest", "", 5],
    ["wearable", "tacs_Vest_PlateCarrier_Khaki", "Vest", "", 5],
    ["wearable", "tacs_Vest_PlateCarrier_MARPAT", "Vest", "", 5],
    ["wearable", "tacs_Vest_Tactical_DarkBlack", "Vest", "", 5],
    // Rifles
    ["rifle", "arifle_MX_F", "Rifle", "", 5],
    ["rifle", "arifle_MXC_F", "Rifle", "", 5],
    ["rifle", "arifle_MX_SW_F", "Rifle", "", 5],
    ["rifle", "hlc_rifle_RU556", "Rifle", "", 5],
    ["rifle", "hlc_rifle_Colt727", "Rifle", "", 5],
    ["rifle", "hlc_rifle_bcmjack", "Rifle", "", 5],
    ["rifle", "hlc_rifle_Bushmaster300", "Rifle", "", 5],
    ["rifle", "hlc_rifle_vendimus", "Rifle", "", 5],
    ["rifle", "hlc_rifle_SAMR", "Rifle", "", 5],
    ["rifle", "hlc_rifle_honeybase", "Rifle", "", 5],
    ["rifle", "hlc_rifle_honeybadger", "Rifle", "", 5],
    ["rifle", "hlc_rifle_l1a1slr", "Rifle", "", 5],
    ["rifle", "hlc_rifle_SLR", "Rifle", "", 5],
    ["rifle", "hlc_rifle_FAL5061", "Rifle", "", 5],
    ["rifle", "hlc_rifle_c1A1", "Rifle", "", 5],
    ["rifle", "hlc_rifle_LAR", "Rifle", "", 5],
    ["rifle", "hlc_rifle_falosw", "Rifle", "", 5],
    ["rifle", "hlc_rifle_g3sg1", "Rifle", "", 5],
    ["rifle", "hlc_rifle_psg1", "Rifle", "", 5],
    ["rifle", "hlc_rifle_g3a3", "Rifle", "", 5],
    ["rifle", "hlc_rifle_g3ka4", "Rifle", "", 5],
    ["rifle", "hlc_rifle_hk53", "Rifle", "", 5],
    ["rifle", "hlc_rifle_ak74", "Rifle", "", 5],
    ["rifle", "hlc_rifle_aks74", "Rifle", "", 5],
    ["rifle", "hlc_rifle_aks74u", "Rifle", "", 5],
    ["rifle", "hlc_rifle_ak47", "Rifle", "", 5],
    ["rifle", "hlc_rifle_akm", "Rifle", "", 5],
    ["rifle", "hlc_rifle_rpk", "Rifle", "", 5],
    ["rifle", "hlc_rifle_ak12", "Rifle", "", 5],
    ["rifle", "hlc_rifle_aughbar", "Rifle", "", 5],
    ["rifle", "hlc_rifle_aughbar_b", "Rifle", "", 5],
    ["rifle", "hlc_rifle_aughbar_t", "Rifle", "", 5],
    ["rifle", "hlc_rifle_auga2lsw", "Rifle", "", 5],
    ["rifle", "hlc_rifle_auga2lsw_t", "Rifle", "", 5],
    ["rifle", "hlc_rifle_auga2lsw_b", "Rifle", "", 5],
    ["rifle", "hlc_rifle_auga3", "Rifle", "", 5],
    ["rifle", "hlc_rifle_auga3_bl", "Rifle", "", 5],
    ["rifle", "hlc_rifle_auga3_b", "Rifle", "", 5],
    ["rifle", "arifle_MX_Black_F", "Rifle", "", 5],
    ["rifle", "arifle_MXC_Black_F", "Rifle", "", 5],
    ["rifle", "arifle_MX_SW_Black_F", "Rifle", "", 5],
    ["rifle", "arifle_MXM_Black_F", "Rifle", "", 5],
    ["rifle", "arifle_TRG20_F", "Rifle", "", 5],
    ["rifle", "arifle_TRG21_F", "Rifle", "", 5],
    ["rifle", "srifle_DMR_03_F", "Rifle", "", 5],
    ["rifle", "srifle_DMR_03_khaki_F", "Rifle", "", 5],
    ["rifle", "srifle_DMR_03_tan_F", "Rifle", "", 5],
    ["rifle", "srifle_DMR_03_multicam_F", "Rifle", "", 5],
    ["rifle", "srifle_DMR_03_woodland_F", "Rifle", "", 5],
    ["rifle", "arifle_Mk20_F", "Rifle", "", 5],
    ["rifle", "arifle_Mk20_plain_F", "Rifle", "", 5],
    ["rifle", "arifle_Mk20C_F", "Rifle", "", 5],
    ["rifle", "arifle_Mk20C_plain_F", "Rifle", "", 5],
    ["rifle", "hlc_rifle_aku12", "Rifle", "", 5],
    ["rifle", "hlc_rifle_rpk12", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36A1", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36KA1", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36C", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36E1", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36KE1", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36V", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36KV", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36CV", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36KTAC", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36CTAC", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36MLIC", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36KMLIC", "Rifle", "", 5],
    ["rifle", "hlc_rifle_G36CMLIC", "Rifle", "", 5],
    ["rifle", "hlc_rifle_STGW57", "Rifle", "", 5],
    ["rifle", "hlc_rifle_stgw57_RIS", "Rifle", "", 5],
    ["rifle", "hlc_rifle_stgw57_command", "Rifle", "", 5],
    ["rifle", "hlc_rifle_sig5104", "Rifle", "", 5],
    ["rifle", "hlc_rifle_amt", "Rifle", "", 5],
    ["rifle", "hlc_rifle_M4", "Rifle", "", 5],
    ["rifle", "hlc_rifle_CQBR", "Rifle", "", 5],
    ["rifle", "tacs_MX_BlackCamo", "Rifle", "", 5],
    ["rifle", "arifle_MXM_F", "Marksman Rifle", "", 5],
    ["rifle", "hlc_rifle_M14", "Marksman Rifle", "", 5],
    ["rifle", "hlc_rifle_M21", "Marksman Rifle", "", 5],
    ["rifle", "hlc_rifle_M14DMR", "Marksman Rifle", "", 5],
    ["rifle", "arifle_MXM_Black_F", "Marksman Rifle", "", 5],
    ["rifle", "srifle_DMR_06_camo_F", "Marksman Rifle", "", 5],
    ["rifle", "srifle_DMR_06_olive_F", "Marksman Rifle", "", 5],
    // Magazines
    ["ammo", "9Rnd_45ACP_Mag", "Ammo", "", 20],
    ["ammo", "11Rnd_45ACP_Mag", "Ammo", "", 20],
    ["ammo", "200Rnd_65x39_cased_Box", "Ammo", "", 20],
    ["ammo", "ACE_200Rnd_65x39_cased_Box_Tracer_Dim", "Ammo", "", 20],
    ["ammo", "16Rnd_9x21_Mag", "Ammo", "", 20],
    ["ammo", "30Rnd_65x39_caseless_mag", "Ammo", "", 20],
    ["ammo", "ACE_30Rnd_65x39_caseless_mag_Tracer_Dim", "Ammo", "", 20],
    ["ammo", "100Rnd_65x39_caseless_mag", "Ammo", "", 20],
    ["ammo", "ACE_100Rnd_65x39_caseless_mag_Tracer_Dim", "Ammo", "", 20],
    ["ammo", "30rnd_556x45_stanag", "Ammo", "", 20],
    ["ammo", "6Rnd_45ACP_Cylinder", "Ammo", "", 20],
    ["ammo", "20rnd_556x45_uw_mag", "Ammo", "", 20],
    ["ammo", "ACE_30Rnd_65x39_caseless_green_mag_Tracer_D", "Ammo", "", 20],
    ["ammo", "ACE_30Rnd_556x45_Stanag_M995_AP_mag", "Ammo", "", 20],
    ["ammo", "ACE_30Rnd_556x45_Stanag_Mk262_mag", "Ammo", "", 20],
    ["ammo", "ACE_30Rnd_556x45_Stanag_Mk318_mag", "Ammo", "", 20],
    ["ammo", "ACE_30Rnd_556x45_Stanag_Tracer_Dim", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_Mag_Tracer", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_Mag_Tracer_Dim", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_Mag_SD", "Ammo", "", 20],
    ["ammo", "ACE_10Rnd_762x51_M118LR_Mag", "Ammo", "", 20],
    ["ammo", "ACE_10Rnd_762x51_Mk316_Mod_0_Mag", "Ammo", "", 20],
    ["ammo", "ACE_10Rnd_762x51_Mk319_Mod_0_Mag", "Ammo", "", 20],
    ["ammo", "ACE_10Rnd_762x51_M993_AP_Mag", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_M118LR_Mag", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_M993_AP_Mag", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x67_Mk248_Mod_0_Mag", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x67_Mk248_Mod_1_Mag", "Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x67_Berger_Hybrid_OTM_Mag", "Ammo", "", 20],
    ["ammo", "ACE_10Rnd_338_300gr_HPBT_Mag", "Ammo", "", 20],
    ["ammo", "ACE_10Rnd_338_API526_Mag", "Ammo", "", 20],
    ["ammo", "ACE_10Rnd_762x54_Tracer_mag", "Ammo", "", 20],
    ["ammo", "ACE_30Rnd_9x19_mag", "Ammo", "", 20],
    ["ammo", "ACE_16Rnd_9x19_mag", "Ammo", "", 20],
    ["ammo", "29Round_300BLK_STANAG", "Ammo", "", 20],
    ["ammo", "29Round_300BLK_STANAG_T", "Ammo", "", 20],
    ["ammo", "29Round_300BLK_STANAG_S", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_556x45_EPR", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_556x45_SOST", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_556x45_SPR", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_B_fal", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_t_fal", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_S_fal", "Ammo", "", 20],
    ["ammo", "hlc_50Rnd_762x51_M_FAL", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_B_G3", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_T_G3", "Ammo", "", 20],
    ["ammo", "hlc_50Rnd_762x51_M_G3", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_B_M14", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_T_M14", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_545x39_B_AK", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_545x39_T_AK", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_545x39_EP_AK", "Ammo", "", 20],
    ["ammo", "hlc_45Rnd_545x39_t_rpk", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_762x39_b_ak", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_762x39_t_ak", "Ammo", "", 20],
    ["ammo", "hlc_45Rnd_762x39_t_rpk", "Ammo", "", 20],
    ["ammo", "hlc_45Rnd_762x39_m_rpk", "Ammo", "", 20],
    ["ammo", "hlc_100Rnd_762x51_B_M60E4", "Ammo", "", 20],
    ["ammo", "hlc_100Rnd_762x51_T_M60E4", "Ammo", "", 20],
    ["ammo", "hlc_100Rnd_762x51_M_M60E4", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_9x19_B_MP5", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_9x19_GD_MP5", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_9x19_SD_MP5", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_10mm_B_MP5", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_10mm_JHP_MP5", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_556x45_B_AUG", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_556x45_SOST_AUG", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_556x45_SPR_AUG", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_556x45_T_AUG", "Ammo", "", 20],
    ["ammo", "hlc_40Rnd_556x45_B_AUG", "Ammo", "", 20],
    ["ammo", "hlc_40Rnd_556x45_SOST_AUG", "Ammo", "", 20],
    ["ammo", "hlc_40Rnd_556x45_SPR_AUG", "Ammo", "", 20],
    ["ammo", "hlc_25Rnd_9x19mm_M882_AUG", "Ammo", "", 20],
    ["ammo", "hlc_25Rnd_9x19mm_JHP_AUG", "Ammo", "", 20],
    ["ammo", "hlc_25Rnd_9x19mm_subsonic_AUG", "Ammo", "", 20],
    ["ammo", "30rnd_9x21_mag", "Ammo", "", 20],
    ["ammo", "30rnd_45acp_mag_smg_01", "Ammo", "", 20],
    ["ammo", "hlc_30Rnd_545x39_S_AK", "Ammo", "", 20],
    ["ammo", "hlc_10rnd_12g_buck_S12", "Ammo", "", 20],
    ["ammo", "hlc_10rnd_12g_slug_S12", "Ammo", "", 20],
    ["ammo", "hlc_200rnd_556x45_M_SAW", "Ammo", "", 20],
    ["ammo", "hlc_200rnd_556x45_T_SAW", "Ammo", "", 20],
    ["ammo", "hlc_200rnd_556x45_B_SAW", "Ammo", "", 20],
    ["ammo", "150rnd_762x54_box", "Ammo", "", 20],
    ["ammo", "hlc_30rnd_556x45_EPR_G36", "Ammo", "", 20],
    ["ammo", "hlc_30rnd_556x45_SOST_G36", "Ammo", "", 20],
    ["ammo", "hlc_30rnd_556x45_SPR_G36", "Ammo", "", 20],
    ["ammo", "hlc_100rnd_556x45_EPR_G36", "Ammo", "", 20],
    ["ammo", "hlc_5rnd_3006_1903", "Ammo", "", 20],
    ["ammo", "hlc_24Rnd_75x55_B_stgw", "Ammo", "", 20],
    ["ammo", "hlc_24Rnd_75x55_ap_stgw", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_b_amt", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_mk316_amt", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_bball_amt", "Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_T_amt", "Ammo", "", 20],
    ["ammo", "hlc_24Rnd_75x55_T_stgw", "Ammo", "", 20],
    ["ammo", "30Rnd_65x39_caseless_mag", "Marksman Ammo", "", 20],
    ["ammo", "ACE_30Rnd_65x39_caseless_mag_Tracer_Dim", "Marksman Ammo", "", 20],
    ["ammo", "ACE_30Rnd_65x39_caseless_green_mag_Tracer_D", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_Mag_Tracer", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_Mag_Tracer_Dim", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_Mag_SD", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_M118LR_Mag", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x51_M993_AP_Mag", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x67_Mk248_Mod_0_Mag", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x67_Mk248_Mod_1_Mag", "Marksman Ammo", "", 20],
    ["ammo", "ACE_20Rnd_762x67_Berger_Hybrid_OTM_Mag", "Marksman Ammo", "", 20],
    ["ammo", "ACE_30Rnd_9x19_mag", "Marksman Ammo", "", 20],
    ["ammo", "29Round_300BLK_STANAG", "Marksman Ammo", "", 20],
    ["ammo", "29Round_300BLK_STANAG_T", "Marksman Ammo", "", 20],
    ["ammo", "29Round_300BLK_STANAG_S", "Marksman Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_B_M14", "Marksman Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_T_M14", "Marksman Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_b_amt", "Marksman Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_mk316_amt", "Marksman Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_bball_amt", "Marksman Ammo", "", 20],
    ["ammo", "hlc_20Rnd_762x51_T_amt", "Marksman Ammo", "", 20],
    ["ammo", "hlc_24Rnd_75x55_T_stgw", "Marksman Ammo", "", 20],
    // Attachments
    ["attachment", "RH_HBLM", "Attachment", "", 5],
    ["attachment", "RH_HBLM_tg", "Attachment", "", 5],
    ["attachment", "RH_HBLM_des", "Attachment", "", 5],
    ["attachment", "RH_HBLM_wdl", "Attachment", "", 5],
    ["attachment", "RH_TD_ACB", "Attachment", "", 5],
    ["attachment", "RH_TD_ACB_g", "Attachment", "", 5],
    ["attachment", "RH_TD_ACB_b", "Attachment", "", 5],
    ["attachment", "optic_Yorris", "Attachment", "", 5],
    ["attachment", "optic_MRD", "Attachment", "", 5],
    ["attachment", "acc_flashlight", "Attachment", "", 5],
    ["attachment", "ACE_acc_pointer_red", "Attachment", "", 5],
    ["attachment", "ACE_acc_pointer_green_IR", "Attachment", "", 5],
    ["attachment", "ACE_acc_pointer_green", "Attachment", "", 5],
    ["attachment", "RH_peq15", "Attachment", "", 5],
    ["attachment", "RH_peq15_top", "Attachment", "", 5],
    ["attachment", "RH_peq15b", "Attachment", "", 5],
    ["attachment", "RH_peq15b_top", "Attachment", "", 5],
    ["attachment", "RH_peq2", "Attachment", "", 5],
    ["attachment", "RH_peq2_top", "Attachment", "", 5],
    ["attachment", "RH_SFM952V", "Attachment", "", 5],
    ["attachment", "RH_SFM952V_tan", "Attachment", "", 5],
    ["attachment", "RH_pmir", "Attachment", "", 5],
    ["attachment", "RH_A26", "Attachment", "", 5],
    ["attachment", "RH_x2", "Attachment", "", 5],
    ["attachment", "RH_m6x", "Attachment", "", 5],
    ["attachment", "optic_Aco", "Attachment", "", 5],
    ["attachment", "optic_ACO_grn", "Attachment", "", 5],
    ["attachment", "optic_Arco", "Attachment", "", 5],
    ["attachment", "optic_Hamr", "Attachment", "", 5],
    ["attachment", "optic_MRCO", "Attachment", "", 5],
    ["attachment", "optic_Holosight", "Attachment", "", 5],
    ["attachment", "ACE_optic_Arco_2D", "Attachment", "", 5],
    ["attachment", "ACE_optic_SOS_2D", "Attachment", "", 5],
    ["attachment", "ACE_optic_MRCO_2D", "Attachment", "", 5],
    ["attachment", "ACE_optic_Hamr_2D", "Attachment", "", 5],
    ["attachment", "hlc_optic_suit", "Attachment", "", 5],
    ["attachment", "hlc_optic_accupoint_g3", "Attachment", "", 5],
    ["attachment", "hlc_optic_kobra", "Attachment", "", 5],
    ["attachment", "hlc_optic_goshawk", "Attachment", "", 5],
    ["attachment", "optic_ACO_grn_smg", "Attachment", "", 5],
    ["attachment", "optic_Aco_smg", "Attachment", "", 5],
    ["attachment", "optic_Holosight_smg", "Attachment", "", 5],
    ["attachment", "RH_eotech553", "Attachment", "", 5],
    ["attachment", "RH_eotech553mag", "Attachment", "", 5],
    ["attachment", "RH_eotech553_tan", "Attachment", "", 5],
    ["attachment", "RH_eotech553mag_tan", "Attachment", "", 5],
    ["attachment", "RH_eotexps3", "Attachment", "", 5],
    ["attachment", "RH_eotexps3_tan", "Attachment", "", 5],
    ["attachment", "RH_eothhs1", "Attachment", "", 5],
    ["attachment", "RH_eothhs1_tan", "Attachment", "", 5],
    ["attachment", "RH_compm4s", "Attachment", "", 5],
    ["attachment", "RH_compm2", "Attachment", "", 5],
    ["attachment", "RH_compm2l", "Attachment", "", 5],
    ["attachment", "RH_compm2_tan", "Attachment", "", 5],
    ["attachment", "RH_compm2l_tan", "Attachment", "", 5],
    ["attachment", "RH_t1", "Attachment", "", 5],
    ["attachment", "RH_t1_tan", "Attachment", "", 5],
    ["attachment", "RH_reflex", "Attachment", "", 5],
    ["attachment", "RH_shortdot", "Attachment", "", 5],
    ["attachment", "RH_m3lr", "Attachment", "", 5],
    ["attachment", "RH_ta01nsn", "Attachment", "", 5],
    ["attachment", "RH_ta01nsn_2D", "Attachment", "", 5],
    ["attachment", "RH_ta31rco", "Attachment", "", 5],
    ["attachment", "RH_ta31rco_2D", "Attachment", "", 5],
    ["attachment", "RH_ta31rmr", "Attachment", "", 5],
    ["attachment", "RH_ta31rmr_2D", "Attachment", "", 5],
    ["attachment", "RH_ta01nsn_tan", "Attachment", "", 5],
    ["attachment", "RH_ta01nsn_tan_2D", "Attachment", "", 5],
    ["attachment", "RH_ta31rco_tan", "Attachment", "", 5],
    ["attachment", "RH_ta31rco_tan_2D", "Attachment", "", 5],
    ["attachment", "RH_ta31rmr_tan", "Attachment", "", 5],
    ["attachment", "RH_ta31rmr_tan_2D", "Attachment", "", 5],
    ["attachment", "RH_ta648", "Attachment", "", 5],
    ["attachment", "RH_accupoint", "Attachment", "", 5],
    ["attachment", "RH_c79", "Attachment", "", 5],
    ["attachment", "RH_c79_2D", "Attachment", "", 5],
    ["attachment", "RH_m145", "Attachment", "", 5],
    ["attachment", "RH_barska_rds", "Attachment", "", 5],
    ["attachment", "RH_cmore", "Attachment", "", 5],
    ["attachment", "RH_Ltdocter", "Attachment", "", 5],
    ["attachment", "RH_LTdocterl", "Attachment", "", 5],
    ["attachment", "RH_zpoint", "Attachment", "", 5],
    ["attachment", "HLC_Optic_G36dualoptic35x", "Attachment", "", 5],
    ["attachment", "HLC_Optic_G36dualoptic35x2d", "Attachment", "", 5],
    ["attachment", "HLC_Optic_G36Export35x", "Attachment", "", 5],
    ["attachment", "HLC_Optic_G36Export35x2d", "Attachment", "", 5],
    ["attachment", "HLC_Optic_G36Dualoptic15x", "Attachment", "", 5],
    ["attachment", "HLC_Optic_G36Dualoptic15x2d", "Attachment", "", 5],
    ["attachment", "HLC_Optic_G36Export15x", "Attachment", "", 5],
    ["attachment", "HLC_Optic_G36Export15x2d", "Attachment", "", 5],
    ["attachment", "hlc_optic_Kern", "Attachment", "", 5],
    ["attachment", "hlc_optic_Kern2d", "Attachment", "", 5],
    ["attachment", "bipod_01_F_snd", "Attachment", "", 5],
    ["attachment", "bipod_01_F_blk", "Attachment", "", 5],
    ["attachment", "bipod_01_F_mtp", "Attachment", "", 5],
    ["attachment", "RH_HBLM", "Attachment", "", 5],
    ["attachment", "RH_HBLM_tg", "Attachment", "", 5],
    ["attachment", "RH_HBLM_des", "Attachment", "", 5],
    ["attachment", "RH_HBLM_wdl", "Attachment", "", 5],
    ["attachment", "RH_TD_ACB", "Attachment", "", 5],
    ["attachment", "RH_TD_ACB_b", "Attachment", "", 5],
    ["attachment", "RH_TD_ACB_g", "Attachment", "", 5]
]] call TACFUNC(armory,addItems);
