/*
 * Author: Rory
 * Initializes Virtual Arsenal on an object with specific items only.
 *
 * Arguments:
 * 0: Crate <OBJECT>
 *
 * Return Value:
 * None
 *
 * Example:
 * [crate] call TAC_Olympus_fnc_VAboxStagingInit
 */
#include "..\script_component.hpp"

#define AVAILABLE_UNIFORMS [\
    "U_B_HeliPilotCoveralls",\
    "U_I_HeliPilotCoveralls",\
    "tacs_Uniform_Combat_LS_BS_GP_BB",\
    "tacs_Uniform_Combat_LS_BS_GP_TB",\
    "tacs_Uniform_Combat_LS_BS_TP_BB",\
    "tacs_Uniform_Combat_LS_BS_TP_TB",\
    "tacs_Uniform_Combat_LS_GS_BP_BB",\
    "tacs_Uniform_Combat_LS_GS_TP_BB",\
    "tacs_Uniform_Combat_LS_BS_DGP_BB",\
    "tacs_Uniform_Combat_LS_TS_BP_BB",\
    "tacs_Uniform_Combat_LS_TS_GP_BB",\
    "tacs_Uniform_Combat_LS_TS_GP_TB",\
    "tacs_Uniform_Combat_LS_CDBS_GP_TB",\
    "tacs_Uniform_Combat_LS_CLBS_GP_BB",\
    "tacs_Uniform_Combat_LS_CLRS_TP_BB",\
    "tacs_Uniform_Combat_LS_CPS_BP_BB",\
    "tacs_Uniform_Combat_RS_BS_GP_BB",\
    "tacs_Uniform_Combat_RS_BS_GP_TB",\
    "tacs_Uniform_Combat_RS_BS_TP_BB",\
    "tacs_Uniform_Combat_RS_BS_TP_TB",\
    "tacs_Uniform_Combat_RS_GS_BP_BB",\
    "tacs_Uniform_Combat_RS_GS_TP_BB",\
    "tacs_Uniform_Combat_RS_BS_DGP_BB",\
    "tacs_Uniform_Combat_RS_TS_BP_BB",\
    "tacs_Uniform_Combat_RS_TS_GP_BB",\
    "tacs_Uniform_Combat_RS_TS_GP_TB",\
    "tacs_Uniform_Combat_RS_CDBS_GP_TB",\
    "tacs_Uniform_Combat_RS_CLBS_GP_BB",\
    "tacs_Uniform_Combat_RS_CLRS_TP_BB",\
    "tacs_Uniform_Combat_RS_CPS_BP_BB",\
    "tacs_Uniform_Garment_LS_BS_BP_BB",\
    "tacs_Uniform_Garment_LS_BS_GP_BB",\
    "tacs_Uniform_Garment_LS_BS_EP_TB",\
    "tacs_Uniform_Garment_LS_GS_GP_BB",\
    "tacs_Uniform_Garment_LS_GS_BP_BB",\
    "tacs_Uniform_Garment_LS_GS_EP_TB",\
    "tacs_Uniform_Garment_LS_ES_EP_TB",\
    "tacs_Uniform_Garment_LS_ES_BP_BB",\
    "tacs_Uniform_Garment_LS_ES_GP_BB",\
    "tacs_Uniform_Garment_LS_TS_TP_TB",\
    "tacs_Uniform_Garment_LS_GS_TP_TB",\
    "tacs_Uniform_Garment_LS_TS_GP_BB",\
    "tacs_Uniform_Garment_LS_BS_TP_TB",\
    "tacs_Uniform_Garment_LS_TS_BP_BB",\
    "tacs_Uniform_Garment_RS_BS_BP_BB",\
    "tacs_Uniform_Garment_RS_BS_GP_BB",\
    "tacs_Uniform_Garment_RS_BS_EP_TB",\
    "tacs_Uniform_Garment_RS_GS_GP_BB",\
    "tacs_Uniform_Garment_RS_GS_BP_BB",\
    "tacs_Uniform_Garment_RS_GS_EP_TB",\
    "tacs_Uniform_Garment_RS_ES_EP_TB",\
    "tacs_Uniform_Garment_RS_ES_BP_BB",\
    "tacs_Uniform_Garment_RS_ES_GP_BB",\
    "tacs_Uniform_Garment_RS_TS_TP_TB",\
    "tacs_Uniform_Garment_RS_GS_TP_TB",\
    "tacs_Uniform_Garment_RS_TS_GP_BB",\
    "tacs_Uniform_Garment_RS_BS_TP_TB",\
    "tacs_Uniform_Garment_RS_TS_BP_BB",\
    "tacs_Uniform_Polo_TP_LS_TP_TB",\
    "tacs_Uniform_Polo_TP_TS_GP_BB",\
    "tacs_Uniform_Polo_TP_BS_TP_TB",\
    "tacs_Uniform_Polo_TP_BS_LP_BB",\
    "tacs_Uniform_Polo_TP_LS_GP_BB",\
    "tacs_Uniform_Polo_TP_OS_TP_BB",\
    "tacs_Uniform_Polo_TP_OS_LP_BB",\
    "tacs_Uniform_Polo_TP_GS_TP_TB",\
    "tacs_Uniform_Polo_TP_WS_TP_TB",\
    "tacs_Uniform_Polo_TP_WS_LP_BB",\
    "tacs_Uniform_Polo_TP_WS_GP_BB",\
    "tacs_Uniform_Polo_CP_LS_TP_OB",\
    "tacs_Uniform_Polo_CP_RS_LP_BB",\
    "tacs_Uniform_Polo_CP_BS_TP_BB",\
    "tacs_Uniform_TShirt_JP_GS_LP_BB",\
    "tacs_Uniform_TShirt_JP_GS_TP_BB",\
    "tacs_Uniform_TShirt_JP_BS_LP_BB",\
    "tacs_Uniform_TShirt_JP_BS_TP_BB",\
    "tacs_Uniform_TShirt_JP_LS_TP_BB",\
    "tacs_Uniform_TShirt_JP_WS_LP_BB"\
]

#define AVAILABLE_GOGGLES [\
    "G_Shades_Black",\
    "G_Shades_Blue",\
    "G_Sport_Blackred",\
    "G_Spectacles",\
    "G_Spectacles_Tinted",\
    "G_Combat",\
    "G_Lowprofile",\
    "G_Shades_Green",\
    "G_Shades_Red",\
    "G_Sport_BlackWhite",\
    "G_Sport_Blackyellow",\
    "G_Sport_Greenblack",\
    "G_Sport_Checkered",\
    "G_Sport_Red",\
    "G_Tactical_Black",\
    "G_Bandanna_aviator",\
    "G_Bandanna_blk",\
    "G_Bandanna_khk",\
    "G_Bandanna_oli",\
    "G_Bandanna_shades",\
    "G_Bandanna_sport",\
    "G_Bandanna_tan",\
    "ACE_NVG_Gen1",\
    "ACE_NVG_Gen2",\
    "ACE_NVG_Gen4",\
    "ACE_NVG_Wide",\
    "G_Aviator",\
    "NVGoggles_OPFOR",\
    "NVGoggles",\
    "NVGoggles_INDEP",\
    "tacs_Goggles_Black",\
    "tacs_Goggles_Green",\
    "tacs_Goggles_Tan"\
]

#define AVAILABLE_BACKPACKS [\
    "B_AssaultPack_blk",\
    "B_AssaultPack_cbr",\
    "B_AssaultPack_mcamo",\
    "B_AssaultPack_ocamo",\
    "B_AssaultPack_rgr",\
    "B_AssaultPack_sgg",\
    "B_FieldPack_ocamo_Medic",\
    "B_Carryall_ocamo",\
    "B_Carryall_oli",\
    "B_Carryall_cbr",\
    "B_Kitbag_sgg",\
    "B_Kitbag_mcamo",\
    "B_FieldPack_blk",\
    "B_FieldPack_ocamo",\
    "B_FieldPack_oucamo",\
    "B_FieldPack_cbr",\
    "tacs_Backpack_AssaultExpanded_Black",\
    "tacs_Backpack_AssaultExpanded_Green",\
    "tacs_Backpack_AssaultExpanded_Tan",\
    "tacs_Backpack_Carryall_DarkBlack",\
    "tacs_Backpack_Kitbag_DarkBlack"\
]

#define AVAILABLE_HEADGEAR [\
    "H_Booniehat_khk_hs",\
    "H_Booniehat_khk",\
    "H_HelmetB",\
    "H_HelmetB_light",\
    "H_HelmetB_paint",\
    "H_PilotHelmetHeli_B",\
    "H_PilotHelmetHeli_O",\
    "H_CrewHelmetHeli_B",\
    "H_Cap_red",\
    "H_Cap_blu",\
    "H_Cap_oli",\
    "H_Cap_headphones",\
    "H_Cap_tan",\
    "H_Cap_blk",\
    "H_Cap_brn_SPECOPS",\
    "H_Cap_tan_specops_US",\
    "H_Cap_khaki_specops_UK",\
    "H_Cap_grn",\
    "H_Cap_blk_Raven",\
    "H_Cap_oli_hs",\
    "H_Cap_usblack",\
    "H_Bandanna_khk",\
    "H_Bandanna_khk_hs",\
    "H_Bandanna_cbr",\
    "H_Bandanna_sgg",\
    "H_Bandanna_sand",\
    "H_Bandanna_gry",\
    "H_Bandanna_blu",\
    "H_Bandanna_camo",\
    "H_Bandanna_mcamo",\
    "H_Booniehat_oli",\
    "H_Watchcap_blk",\
    "H_Watchcap_camo",\
    "H_Watchcap_cbr",\
    "H_Watchcap_khk",\
    "H_Booniehat_DMARPAT",\
    "H_Booniehat_GCAMO",\
    "H_Booniehat_rgr",\
    "H_CrewHelmetHeli_O",\
    "H_HelmetB_plain_blk",\
    "H_Helmet_Kerry",\
    "H_HelmetB_black",\
    "H_HelmetB_desert",\
    "H_HelmetB_grass",\
    "H_HelmetB_sand",\
    "H_HelmetB_snakeskin",\
    "H_HelmetIA",\
    "tacs_Cap_Headphones_BlackLogo",\
    "tacs_Cap_BlackLogo",\
    "tacs_Cap_TanLogo",\
    "tacs_Cap_Earpiece_BlackLogo",\
    "tacs_Cap_Earpiece_TanLogo",\
    "tacs_Cap_Backwards_BlackLogo",\
    "tacs_Cap_Backwards_TanLogo",\
    "tacs_Helmet_Ballistic_DarkBlack",\
    "tacs_Helmet_PilotHeli_Tan",\
    "tacs_Hat_Boonie_RangerGreen",\
    "tacs_Hat_Boonie_DesertMARPAT",\
    "tacs_Hat_Boonie_Woodland",\
    "tacs_Hat_Boonie_UCP"\
]

#define AVAILABLE_VESTS [\
    "V_PlateCarrier1_rgr",\
    "V_PlateCarrier2_rgr",\
    "V_TacVest_brn",\
    "V_TacVest_oli",\
    "V_PlateCarrierH_CTRG",\
    "V_PlateCarrierL_CTRG",\
    "V_RebreatherB",\
    "V_Rangemaster_belt",\
    "V_BandollierB_khk",\
    "V_BandollierB_cbr",\
    "V_BandollierB_rgr",\
    "V_BandollierB_blk",\
    "V_BandollierB_oli",\
    "V_PlateCarrier3_rgr",\
    "V_PlateCarrierGL_rgr",\
    "V_PlateCarrier1_blk",\
    "V_PlateCarrierSpec_rgr",\
    "V_Chestrig_khk",\
    "V_Chestrig_rgr",\
    "V_Chestrig_blk",\
    "V_Chestrig_oli",\
    "V_TacVest_khk",\
    "V_TacVest_blk",\
    "V_TacVest_camo",\
    "V_TacVestIR_blk",\
    "V_TacVestCamo_khk",\
    "V_HarnessO_brn",\
    "V_HarnessOGL_brn",\
    "V_HarnessO_gry",\
    "V_HarnessOGL_gry",\
    "V_HarnessOSpec_brn",\
    "V_HarnessOSpec_gry",\
    "V_PlateCarrierIA1_dgtl",\
    "V_PlateCarrierIA2_dgtl",\
    "tacs_Vest_PlateCarrierFull_Black",\
    "tacs_Vest_PlateCarrierFull_Green",\
    "tacs_Vest_PlateCarrier_Black",\
    "tacs_Vest_PlateCarrier_Green",\
    "tacs_Vest_PlateCarrier_Coyote",\
    "tacs_Vest_PlateCarrier_Khaki",\
    "tacs_Vest_PlateCarrier_MARPAT",\
    "tacs_Vest_Tactical_DarkBlack"\
]

#define AVAILABLE_RIFLES [\
    "arifle_MX_F",\
    "arifle_MXC_F",\
    "arifle_MX_SW_F",\
    "hlc_rifle_RU556",\
    "hlc_rifle_Colt727",\
    "hlc_rifle_bcmjack",\
    "hlc_rifle_Bushmaster300",\
    "hlc_rifle_vendimus",\
    "hlc_rifle_SAMR",\
    "hlc_rifle_honeybase",\
    "hlc_rifle_honeybadger",\
    "hlc_rifle_l1a1slr",\
    "hlc_rifle_SLR",\
    "hlc_rifle_FAL5061",\
    "hlc_rifle_c1A1",\
    "hlc_rifle_LAR",\
    "hlc_rifle_falosw",\
    "hlc_rifle_g3sg1",\
    "hlc_rifle_psg1",\
    "hlc_rifle_g3a3",\
    "hlc_rifle_g3ka4",\
    "hlc_rifle_hk53",\
    "hlc_rifle_ak74",\
    "hlc_rifle_aks74",\
    "hlc_rifle_aks74u",\
    "hlc_rifle_ak47",\
    "hlc_rifle_akm",\
    "hlc_rifle_rpk",\
    "hlc_rifle_ak12",\
    "hlc_rifle_aughbar",\
    "hlc_rifle_aughbar_b",\
    "hlc_rifle_aughbar_t",\
    "hlc_rifle_auga2lsw",\
    "hlc_rifle_auga2lsw_t",\
    "hlc_rifle_auga2lsw_b",\
    "hlc_rifle_auga3",\
    "hlc_rifle_auga3_bl",\
    "hlc_rifle_auga3_b",\
    "arifle_MX_Black_F",\
    "arifle_MXC_Black_F",\
    "arifle_MX_SW_Black_F",\
    "arifle_MXM_Black_F",\
    "arifle_TRG20_F",\
    "arifle_TRG21_F",\
    "srifle_DMR_03_F",\
    "srifle_DMR_03_khaki_F",\
    "srifle_DMR_03_tan_F",\
    "srifle_DMR_03_multicam_F",\
    "srifle_DMR_03_woodland_F",\
    "arifle_Mk20_F",\
    "arifle_Mk20_plain_F",\
    "arifle_Mk20C_F",\
    "arifle_Mk20C_plain_F",\
    "hlc_rifle_aku12",\
    "hlc_rifle_rpk12",\
    "hlc_rifle_G36A1",\
    "hlc_rifle_G36KA1",\
    "hlc_rifle_G36C",\
    "hlc_rifle_G36E1",\
    "hlc_rifle_G36KE1",\
    "hlc_rifle_G36V",\
    "hlc_rifle_G36KV",\
    "hlc_rifle_G36CV",\
    "hlc_rifle_G36KTAC",\
    "hlc_rifle_G36CTAC",\
    "hlc_rifle_G36MLIC",\
    "hlc_rifle_G36KMLIC",\
    "hlc_rifle_G36CMLIC",\
    "hlc_rifle_STGW57",\
    "hlc_rifle_stgw57_RIS",\
    "hlc_rifle_stgw57_command",\
    "hlc_rifle_sig5104",\
    "hlc_rifle_amt",\
    "hlc_rifle_M4",\
    "hlc_rifle_CQBR",\
    "tacs_MX_BlackCamo"\
]

#define AVAILABLE_RIFLE_MAGAZINES [\
    "9Rnd_45ACP_Mag",\
    "11Rnd_45ACP_Mag",\
    "200Rnd_65x39_cased_Box",\
    "ACE_200Rnd_65x39_cased_Box_Tracer_Dim",\
    "16Rnd_9x21_Mag",\
    "30Rnd_65x39_caseless_mag",\
    "ACE_30Rnd_65x39_caseless_mag_Tracer_Dim",\
    "100Rnd_65x39_caseless_mag",\
    "ACE_100Rnd_65x39_caseless_mag_Tracer_Dim",\
    "30rnd_556x45_stanag",\
    "6Rnd_45ACP_Cylinder",\
    "20rnd_556x45_uw_mag",\
    "ACE_30Rnd_65x39_caseless_green_mag_Tracer_D",\
    "ACE_30Rnd_556x45_Stanag_M995_AP_mag",\
    "ACE_30Rnd_556x45_Stanag_Mk262_mag",\
    "ACE_30Rnd_556x45_Stanag_Mk318_mag",\
    "ACE_30Rnd_556x45_Stanag_Tracer_Dim",\
    "ACE_20Rnd_762x51_Mag_Tracer",\
    "ACE_20Rnd_762x51_Mag_Tracer_Dim",\
    "ACE_20Rnd_762x51_Mag_SD",\
    "ACE_10Rnd_762x51_M118LR_Mag",\
    "ACE_10Rnd_762x51_Mk316_Mod_0_Mag",\
    "ACE_10Rnd_762x51_Mk319_Mod_0_Mag",\
    "ACE_10Rnd_762x51_M993_AP_Mag",\
    "ACE_20Rnd_762x51_M118LR_Mag",\
    "ACE_20Rnd_762x51_Mk319_Mod_0_Mag",\
    "ACE_20Rnd_762x51_M993_AP_Mag",\
    "ACE_20Rnd_762x67_Mk248_Mod_0_Mag",\
    "ACE_20Rnd_762x67_Mk248_Mod_1_Mag",\
    "ACE_20Rnd_762x67_Berger_Hybrid_OTM_Mag",\
    "ACE_10Rnd_338_300gr_HPBT_Mag",\
    "ACE_10Rnd_338_API526_Mag",\
    "ACE_10Rnd_762x54_Tracer_mag",\
    "ACE_30Rnd_9x19_mag",\
    "ACE_16Rnd_9x19_mag",\
    "29Round_300BLK_STANAG",\
    "29Round_300BLK_STANAG_T",\
    "29Round_300BLK_STANAG_S",\
    "hlc_30Rnd_556x45_EPR",\
    "hlc_30Rnd_556x45_SOST",\
    "hlc_30Rnd_556x45_SPR",\
    "hlc_20Rnd_762x51_B_fal",\
    "hlc_20Rnd_762x51_t_fal",\
    "hlc_20Rnd_762x51_S_fal",\
    "hlc_50Rnd_762x51_M_FAL",\
    "hlc_20Rnd_762x51_B_G3",\
    "hlc_20Rnd_762x51_T_G3",\
    "hlc_50Rnd_762x51_M_G3",\
    "hlc_20Rnd_762x51_B_M14",\
    "hlc_20Rnd_762x51_T_M14",\
    "hlc_30Rnd_545x39_B_AK",\
    "hlc_30Rnd_545x39_T_AK",\
    "hlc_30Rnd_545x39_EP_AK",\
    "hlc_45Rnd_545x39_t_rpk",\
    "hlc_30Rnd_762x39_b_ak",\
    "hlc_30Rnd_762x39_t_ak",\
    "hlc_45Rnd_762x39_t_rpk",\
    "hlc_45Rnd_762x39_m_rpk",\
    "hlc_100Rnd_762x51_B_M60E4",\
    "hlc_100Rnd_762x51_T_M60E4",\
    "hlc_100Rnd_762x51_M_M60E4",\
    "hlc_30Rnd_9x19_B_MP5",\
    "hlc_30Rnd_9x19_GD_MP5",\
    "hlc_30Rnd_9x19_SD_MP5",\
    "hlc_30Rnd_10mm_B_MP5",\
    "hlc_30Rnd_10mm_JHP_MP5",\
    "hlc_30Rnd_556x45_B_AUG",\
    "hlc_30Rnd_556x45_SOST_AUG",\
    "hlc_30Rnd_556x45_SPR_AUG",\
    "hlc_30Rnd_556x45_T_AUG",\
    "hlc_40Rnd_556x45_B_AUG",\
    "hlc_40Rnd_556x45_SOST_AUG",\
    "hlc_40Rnd_556x45_SPR_AUG",\
    "hlc_25Rnd_9x19mm_M882_AUG",\
    "hlc_25Rnd_9x19mm_JHP_AUG",\
    "hlc_25Rnd_9x19mm_subsonic_AUG",\
    "30rnd_9x21_mag",\
    "30rnd_45acp_mag_smg_01",\
    "hlc_30Rnd_545x39_S_AK",\
    "hlc_10rnd_12g_buck_S12",\
    "hlc_10rnd_12g_slug_S12",\
    "hlc_200rnd_556x45_M_SAW",\
    "hlc_200rnd_556x45_T_SAW",\
    "hlc_200rnd_556x45_B_SAW",\
    "150rnd_762x54_box",\
    "hlc_30rnd_556x45_EPR_G36",\
    "hlc_30rnd_556x45_SOST_G36",\
    "hlc_30rnd_556x45_SPR_G36",\
    "hlc_100rnd_556x45_EPR_G36",\
    "hlc_5rnd_3006_1903",\
    "hlc_24Rnd_75x55_B_stgw",\
    "hlc_24Rnd_75x55_ap_stgw",\
    "hlc_20Rnd_762x51_b_amt",\
    "hlc_20Rnd_762x51_mk316_amt",\
    "hlc_20Rnd_762x51_bball_amt",\
    "hlc_20Rnd_762x51_T_amt",\
    "hlc_24Rnd_75x55_T_stgw"\
]

#define AVAILABLE_ATTACHMENTS [\
    "RH_HBLM",\
    "RH_HBLM_tg",\
    "RH_HBLM_des",\
    "RH_HBLM_wdl",\
    "RH_TD_ACB",\
    "RH_TD_ACB_g",\
    "RH_TD_ACB_b",\
    "optic_Yorris",\
    "optic_MRD",\
    "acc_flashlight",\
    "ACE_acc_pointer_red",\
    "ACE_acc_pointer_green_IR",\
    "ACE_acc_pointer_green",\
    "RH_peq15",\
    "RH_peq15_top",\
    "RH_peq15b",\
    "RH_peq15b_top",\
    "RH_peq2",\
    "RH_peq2_top",\
    "RH_SFM952V",\
    "RH_SFM952V_tan",\
    "RH_pmir",\
    "RH_A26",\
    "RH_x2",\
    "RH_m6x",\
    "optic_Aco",\
    "optic_ACO_grn",\
    "optic_Arco",\
    "optic_Hamr",\
    "optic_MRCO",\
    "optic_Holosight",\
    "ACE_optic_Arco_2D",\
    "ACE_optic_SOS_2D",\
    "ACE_optic_MRCO_2D",\
    "ACE_optic_Hamr_2D",\
    "hlc_optic_suit",\
    "hlc_optic_accupoint_g3",\
    "hlc_optic_kobra",\
    "hlc_optic_goshawk",\
    "optic_ACO_grn_smg",\
    "optic_Aco_smg",\
    "optic_Holosight_smg",\
    "RH_eotech553",\
    "RH_eotech553mag",\
    "RH_eotech553_tan",\
    "RH_eotech553mag_tan",\
    "RH_eotexps3",\
    "RH_eotexps3_tan",\
    "RH_eothhs1",\
    "RH_eothhs1_tan",\
    "RH_compm4s",\
    "RH_compm2",\
    "RH_compm2l",\
    "RH_compm2_tan",\
    "RH_compm2l_tan",\
    "RH_t1",\
    "RH_t1_tan",\
    "RH_reflex",\
    "RH_shortdot",\
    "RH_m3lr",\
    "RH_ta01nsn",\
    "RH_ta01nsn_2D",\
    "RH_ta31rco",\
    "RH_ta31rco_2D",\
    "RH_ta31rmr",\
    "RH_ta31rmr_2D",\
    "RH_ta01nsn_tan",\
    "RH_ta01nsn_tan_2D",\
    "RH_ta31rco_tan",\
    "RH_ta31rco_tan_2D",\
    "RH_ta31rmr_tan",\
    "RH_ta31rmr_tan_2D",\
    "RH_ta648",\
    "RH_accupoint",\
    "RH_c79",\
    "RH_c79_2D",\
    "RH_m145",\
    "RH_barska_rds",\
    "RH_cmore",\
    "RH_Ltdocter",\
    "RH_LTdocterl",\
    "RH_zpoint",\
    "HLC_Optic_G36dualoptic35x",\
    "HLC_Optic_G36dualoptic35x2d",\
    "HLC_Optic_G36Export35x",\
    "HLC_Optic_G36Export35x2d",\
    "HLC_Optic_G36Dualoptic15x",\
    "HLC_Optic_G36Dualoptic15x2d",\
    "HLC_Optic_G36Export15x",\
    "HLC_Optic_G36Export15x2d",\
    "hlc_optic_Kern",\
    "hlc_optic_Kern2d",\
    "bipod_01_F_snd",\
    "bipod_01_F_blk",\
    "bipod_01_F_mtp",\
    "RH_HBLM",\
    "RH_HBLM_tg",\
    "RH_HBLM_des",\
    "RH_HBLM_wdl",\
    "RH_TD_ACB",\
    "RH_TD_ACB_b",\
    "RH_TD_ACB_g"\
]

//Init stuff
params ["_crate"];

["AmmoboxInit", [_crate, false, {true}]] spawn BIS_fnc_arsenal;

//Populate with predefined items and whatever is already in the crate
[_crate, (backpackCargo _crate) + AVAILABLE_BACKPACKS] call BIS_fnc_addVirtualBackpackCargo;
[_crate, (itemCargo _crate) + AVAILABLE_HEADGEAR + AVAILABLE_GOGGLES + AVAILABLE_UNIFORMS + AVAILABLE_VESTS + AVAILABLE_ATTACHMENTS] call BIS_fnc_addVirtualItemCargo;
[_crate, (magazineCargo _crate) + AVAILABLE_RIFLE_MAGAZINES] call BIS_fnc_addVirtualMagazineCargo;
[_crate, (weaponCargo _crate) + AVAILABLE_RIFLES] call BIS_fnc_addVirtualWeaponCargo;
